### ISSUE TITLE
this project is not valid

### ISSUE THREAD

**Issue by ah3243** [dropecho/unity_footstep#3]
Hi I'm trying to open this with oxs version 12 and unity hub version 3.2.0 but it's giving me a 'this project is not valid' error when i try and open it from unity hub. Do you know what could cause this?
thanks

**Comment by vantreeseba** [comment]
Sorry just saw this, will look into it.
Thanks for bringing it to my attention.

**Comment by ah3243** [comment]
got it working! great project, thanks
